const token = localStorage.getItem("token");
const classData = JSON.parse(localStorage.getItem("class"));
const API_BASE = "https://163.44.103.65/api";
const params = new URLSearchParams(window.location.search);
const mode = params.get("mode") || sessionStorage.getItem("currentWorkMode") || "pickup_only";
const className = document.querySelector("#className"); const message = document.querySelector("#message"); const orderList = document.querySelector("#orderList"); const detailSection = document.querySelector("#detailSection"); const orderElement = document.querySelector("#order"); const totalElement = document.querySelector("#total"); const pickupButton = document.querySelector("#pickupButton"); const backButton = document.querySelector("#backButton");
let currentOrder = null;
if (!token || !classData) window.location.href = "index.html"; className.textContent = classData.name;
function renderDetail(order) { currentOrder = order; detailSection.hidden = false; orderElement.innerHTML = ""; const h=document.createElement("p"); h.innerHTML=order.ticket_number>0?`<strong>注文番号 ${order.ticket_number}</strong>`:`<strong>番号なし</strong>`; orderElement.appendChild(h); for(const item of order.items){const d=document.createElement("div");d.textContent=`${item.product_name} × ${item.quantity}`;orderElement.appendChild(d);} totalElement.textContent=`合計 ${order.total}円`; pickupButton.disabled=order.status!=="paid"; pickupButton.textContent=order.status==="paid"?"受け取り完了":"会計が完了していません"; }
async function loadOrders(){ const directId=Number(params.get("order_id")); if(Number.isInteger(directId)&&directId>0){const r=await fetch(`${API_BASE}/orders/id/${directId}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok){message.textContent=d.message;return;}orderList.hidden=true;renderDetail(d.order);return;} const r=await fetch(`${API_BASE}/orders/unreceived`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok){message.textContent=d.message;return;}orderList.innerHTML="";if(d.orders.length===0){orderList.innerHTML="<p>未受け取りの注文はありません。</p>";return;}for(const order of d.orders){const b=document.createElement("button");b.className="workflow-order-card";const state=order.status==="paid"?"会計済み":"会計待ち";b.innerHTML=`<strong>注文番号 ${order.ticket_number}</strong><span>${state}</span><span>${order.items.map(i=>`${i.product_name} × ${i.quantity}`).join(" / ")}</span>`;b.addEventListener("click",()=>renderDetail(order));orderList.appendChild(b);}}
pickupButton.addEventListener("click",async()=>{if(!currentOrder||currentOrder.status!=="paid")return;pickupButton.disabled=true;try{const r=await fetch(`${API_BASE}/orders/${currentOrder.id}/handed-over`,{method:"POST",headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.message||"受け取り処理に失敗しました");if(mode==="order_accounting_pickup"||mode==="accounting_pickup"){window.location.href="work-select.html";return;}message.textContent="受け取りが完了しました。注文番号を再利用できます。";currentOrder=null;detailSection.hidden=true;orderList.hidden=false;await loadOrders();}catch(e){message.textContent=e.message;pickupButton.disabled=false;}});
backButton.addEventListener("click",()=>{window.location.href=params.get("from")==="work"?"work-select.html":"menu.html";});loadOrders();
